name: urbit_ob
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/XLNT/urbit_ob
author: Matt Condon (shrugs) <matt@bydot.app>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  pointycastle: ^1.0.1
  quiver: ">=2.0.0 <3.0.0"
  logging: "^0.11.3"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
